# The Ant System Algorithm For The Travelling Salesman Problem

Algorithm from the Book **Ant Colony Optimization by Marco Dorigo and Thomas Stützle**

In [9]:
#----------------------------------------
# Chia E. Tungom
# chemago99@yahoo.com
# July 30th 2020
# Shenzhen China
#----------------------------------------

In [10]:
# import libraries

import numpy as np
import math
import random

# Roulette Wheel for Probability

In [11]:
# probability and selection using roulette wheel 

# Calculate cumulative sum for roulette wheel 
def PPi(pi):
    n = len(pi)
    ans = []
    
    for i in range(n):
        ans.append( sum([i for i in pi[:i+1]]) )
    return ans 

# Roulette Wheel 
def Roulette(ppi, Pop):
    n = len(ppi)
    ra = random.random()
    
    for i in range(n):
        if i == 0 :
            if ra > 0 and ra < ppi[i]:
                return Pop[i]
        else:
            if ra > ppi[i-1] and ra < ppi[i]:
                return Pop[i]

# Calculate Route Cost

In [12]:
# calculate cost of each route
def Cost(Pop, Cmatrix):
    Cvector = []
    
    for i in range(len(Pop)):
        route = Pop[i]
        cost = 0
        
        for j in range(len(route)-1):
            cost += Cmatrix[route[j]][route[j+1]]
        cost += Cmatrix[route[0]][route[len(route)-1]]   
        Cvector.append(cost)
        
    return Cvector

# Initialize Pheromone 

In [13]:

def TSPher(graph):
    
    n = len(graph)
    route = [i for i in range(n)]
    random.shuffle(route)
    
    cost = Cost([route], graph)[0]
    pher = [[cost for i in range(n)] for j in range(n)]
    
    return pher

# Calculate Transition Probability

In [14]:
# Transition Probability
def TransitionP(connections, alpha, beta):
    """ Takes a list of tuples [(pheromone, distance, hob), ... , (pheromone, distance, hob)]
        return trasition probability for each hob [(probability, hob), ... , (probability, hob)]"""
    
    total = sum( [ (i[0]**alpha)*(i[1]**beta) for i in connections])    # sum heuristic and pheromone info
    prob = [( (((i**alpha)*(j**beta))/total) , k) for i,j,k in connections ]  # probability of each hob
    
    return prob

# pheromone, distance and hob information
def DPH(phermatrix, graph, connections, preshob):
    """ DPH(Distance Pheromone hob)
        takes a pheromone matrix
        graph matrix 
        connections in graph to use 
        present hob in graph
        and return the pheromone, distance and hob [(pheromone, distance, hob), ... , (pheromone, distance, hob)]"""
    
    dph = []
    for i in range(len(connections)):
        if connections[i] > 0:
            dph.append( (phermatrix[preshob][i], 1/graph[preshob][i], i) )
            
    #dph = [(phermatrix[preshob][i], graph[preshob][i], i) for i in range(len(connections)) if connections[i] > 0 ]
    
    return dph

def Disconnect(visited, connections):
    """ Disconnects already visited hobs
    visited: already visited hobs
    connections: connection vector with 0: no connection x: length of connection"""
    
    for i in visited:
        connections[i] = 0
        #print(i, visited, connections)
    #print("DONE++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++DONE")
    return connections

# Find Path 

In [15]:
def FindPath(phermatrix, graph, takeoff, alpha = 2, beta = 2):
    
    path = []
    path.append(takeoff)
    
    while len(path) != len(graph):
        
        Cons = graph[takeoff].copy()
        tabu = path.copy()
        Cons = Disconnect(tabu, Cons)
        HP = DPH(phermatrix, graph, Cons, takeoff)
        prob = TransitionP(HP, alpha, beta)
        takeoff = Roulette(PPi([i[0] for i in prob]), [i[1] for i in prob])
        
        path.append(takeoff)
 
    return path

# Update Pheromone 

In [16]:
# Update Pheromone in visited arcs

def UpPheromone(route, matrix):
    """route : route taken
    matrix: pheromone matrix"""
    
    tau = 1/Cost([route], matrix)[0]
    #tau = 1
    
    for i in range(len(route)-1):
        
        matrix[route[i]][route[i+1]] += tau
        matrix[route[i+1]][route[i]] += tau
    
    # add pheromone to last and first route for TSP
    matrix[route[-1]][route[0]] += tau
    matrix[route[0]][route[-1]] += tau

    return matrix


# Ant Cycle
def UpPheromoneANTC(route, matrix, Q = 1):
    """route : route taken
    matrix: pheromone matrix
    Q: a constant """
    
    tau = Q/Cost([route], matrix)[0]
    #tau = 1
    
    for i in range(len(route)-1):
        
        matrix[route[i]][route[i+1]] += tau
        matrix[route[i+1]][route[i]] += tau
    
    # add pheromone to last and first route for TSP
    matrix[route[-1]][route[0]] += tau
    matrix[route[0]][route[-1]] += tau

    return matrix

# Ant Density
def UpPheromoneANTD(route, matrix, Q = 1):
    """route : route taken
    matrix: pheromone matrix
    Q: a constant """
   
    for i in range(len(route)-1):
        
        matrix[route[i]][route[i+1]] += Q
        matrix[route[i+1]][route[i]] += Q
    
    # add pheromone to last and first route for TSP
    matrix[route[-1]][route[0]] += Q
    matrix[route[0]][route[-1]] += Q

    return matrix

# Ant Quantity
def UpPheromoneANTQ(route, matrix, Q = 1):
    """route : route taken
    matrix: pheromone matrix
    Q: a constant """
   
    for i in range(len(route)-1):
        
        tau = Q/matrix[route[i]][route[i+1]]
        matrix[route[i]][route[i+1]] += tau
        matrix[route[i+1]][route[i]] += tau
    
    # add pheromone to last and first route for TSP
    tau = Q/matrix[route[-1]][route[0]]
    matrix[route[-1]][route[0]] += tau
    matrix[route[0]][route[-1]] += tau

    return matrix

# Evaporate Pheromone 

In [17]:
def EvPheromone(matrix, rho):
    
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j] > 0:
                matrix[i][j] = (1-rho)*matrix[i][j]
            else:
                matrix[i][j] = math.exp(-5)
    return matrix

def EvPheromoneNeg(matrix, rho):
    
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            matrix[i][j] = (1-rho)*matrix[i][j]
        
    return matrix

# Generate a Toy Symmetric TSP Problem 

In [18]:
# A random graph
def Graph(dim, bounds):
    b = [(i, str(i)) for i in range(dim)]   
    matrix = []
    
    for i,j in b:
        j=[]
        if i == 0:
            j.append(0)
            matrix.append(j)
        else:
            for k in range(i+1):
                if k == i:
                    j.append(0)
                else:
                    j.append(random.choice([random.randint(bounds[0], bounds[1])]))  # route length
            matrix.append(j)
            
    M = matrix        
    for i in range(len(M)):
        
        for j in range(1,len(M)-len(M[i])+1):
            M[i].append(M[i+j][i]) 
            
    return M

# Ant System Algorithm

In [19]:
def AS(Ngraph, ants, alpha = 1, beta = 3, rho = 0.5, runs = 50, Pher = None):
    
    if Pher == None:
        Pher = TSPher(Ngraph) 
        
    starthob = random.choice([i for i in range(len(Ngraph))])
    i = 0
    while i < runs:
        Ants = []
        #starthob = random.choice([i for i in range(len(Ngraph))])
        
        for j in range(ants):
            stof = FindPath(Pher, Ngraph, starthob, alpha, beta)
            Ants.append(stof)
   
        #Pheromone update
     
        for j in Ants:
            #Pher = UpPheromone(j, Pher)
            UpPheromoneANTC(j, Pher, 1)  # ant cycle
            #UpPheromoneANTD(j, Pher, 1)  # ant density
            #UpPheromoneANTQ(j, Pher, 1)  # Ant Quantity
            
        #Pheromone update  
        #EvPheromone(Pher, rho)
        EvPheromoneNeg(Pher, rho)
        
        if i%int(runs*0.05) == 0:
            C = Cost(Ants, Ngraph)
            print("In Generation ", i, " The Minimum Cost Found is = ", min(C), "  and the Maximum Cost Found is = ", max(C))
            
        i += 1 

    C = Cost(Ants, Ngraph)    
    print("Minimum Cost Found = ", min(C), "Maximum Cost Found = ", max(C))
    return np.array(Ants), min(C) #, np.array(Pher)

# Example on the Toy Problem

In [22]:
# Toy Network graph 
D = 10
bounds = (2,10)
random.seed(10)
graph = Graph(D, bounds)

np.array(graph)

array([[ 0,  2,  9,  9,  7,  8,  5, 10,  6,  9],
       [ 2,  0,  5,  4,  5,  6,  8,  8, 10,  6],
       [ 9,  5,  0, 10,  2,  9,  2,  3,  4, 10],
       [ 9,  4, 10,  0,  4,  6,  4, 10,  7,  3],
       [ 7,  5,  2,  4,  0,  4,  6,  5,  3,  9],
       [ 8,  6,  9,  6,  4,  0,  5,  5,  9,  4],
       [ 5,  8,  2,  4,  6,  5,  0,  2,  5,  4],
       [10,  8,  3, 10,  5,  5,  2,  0,  8,  7],
       [ 6, 10,  4,  7,  3,  9,  5,  8,  0,  8],
       [ 9,  6, 10,  3,  9,  4,  4,  7,  8,  0]])

In [23]:
# Find Shortest Path with the Algorithm

ants = len(graph)
alpha = 1
beta = 3
rho = 0.5
runs = 200

AS(graph, ants, alpha, beta, rho, runs)

In Generation  0  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  47
In Generation  10  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  50
In Generation  20  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  41
In Generation  30  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  40  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  50  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  60  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  70  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  80  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  90  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  100  The Minimum Cost Found is =  34   and the Maximum Cost Found is =  34
In Generation  110  T

(array([[6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5],
        [6, 7, 2, 4, 8, 0, 1, 3, 9, 5]]), 34)

# Soving Real TSP problems 

In [26]:
# att48

import RouteMatrix as RM
path = './Data/att48.txt'
graph = RM.TSRM(path)


ants = len(graph)
alpha = 1
beta = 4
rho = 0.05
runs = 200

AS(graph, ants, alpha, beta, rho, runs)

In Generation  0  The Minimum Cost Found is =  39723.99538664912   and the Maximum Cost Found is =  59083.479835798826
In Generation  10  The Minimum Cost Found is =  40285.56325812245   and the Maximum Cost Found is =  67493.65396394003
In Generation  20  The Minimum Cost Found is =  43419.9216669635   and the Maximum Cost Found is =  62549.526900680205
In Generation  30  The Minimum Cost Found is =  41480.81579592538   and the Maximum Cost Found is =  62671.04243199685
In Generation  40  The Minimum Cost Found is =  39846.169951941985   and the Maximum Cost Found is =  60614.50237136311
In Generation  50  The Minimum Cost Found is =  42375.85160714432   and the Maximum Cost Found is =  60891.49991173873
In Generation  60  The Minimum Cost Found is =  41502.05477548797   and the Maximum Cost Found is =  65628.34521031249
In Generation  70  The Minimum Cost Found is =  42029.027633495825   and the Maximum Cost Found is =  63137.91117921977
In Generation  80  The Minimum Cost Found is =

(array([[38, 31, 14, ...,  4, 20,  1],
        [38, 31, 20, ..., 40, 15, 28],
        [38, 31, 20, ..., 23, 44, 34],
        ...,
        [38, 31, 13, ..., 28, 40,  1],
        [38, 31, 41, ..., 29, 16, 35],
        [38, 31, 32, ...,  1, 34, 44]]), 40848.54873306147)

In [27]:
import RouteMatrix as RM
path = './Data/burma14.txt'
graph = RM.TSRM(path)


ants = len(graph)
#ants = 100
alpha = 1
beta = 4
rho = 0.05
runs = 1000

AS(graph, ants, alpha, beta, rho, runs)

In Generation  0  The Minimum Cost Found is =  36.733624017913485   and the Maximum Cost Found is =  47.74419282320973
In Generation  50  The Minimum Cost Found is =  36.733624017913485   and the Maximum Cost Found is =  46.56148859029704
In Generation  100  The Minimum Cost Found is =  35.16528840113981   and the Maximum Cost Found is =  44.64134130405837
In Generation  150  The Minimum Cost Found is =  31.456233837620534   and the Maximum Cost Found is =  42.121810905522096
In Generation  200  The Minimum Cost Found is =  34.726251177601064   and the Maximum Cost Found is =  40.66808365605398
In Generation  250  The Minimum Cost Found is =  36.50430528972049   and the Maximum Cost Found is =  40.66808365605398
In Generation  300  The Minimum Cost Found is =  36.391841716646354   and the Maximum Cost Found is =  41.21791786624304
In Generation  350  The Minimum Cost Found is =  36.50430528972049   and the Maximum Cost Found is =  45.15449278628246
In Generation  400  The Minimum Cost 

(array([[ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0, 10,  8,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0, 10,  8,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0, 10,  8,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0, 10,  8,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0, 10,  8,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0, 10,  8,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4],
        [ 2, 13, 11,  5,  6, 12,  7,  0,  8, 10,  9,  1,  3,  4]]),
 36.50430528972049)