# The Elite Ant System Algorithm For The Travelling Salesman Problem

Algorithm from the Book **Ant Colony Optimization by Marco Dorigo and Thomas Stützle**

In [14]:
#----------------------------------------
# Chia E. Tungom
# chemago99@yahoo.com
# July 30th 2020
# Shenzhen China
#----------------------------------------

In [15]:
# import libraries

import numpy as np
import math
import random

# Roulette Wheel for Probability

In [16]:
# probability and selection using roulette wheel 

# Calculate cumulative sum for roulette wheel 
def PPi(pi):
    """ pi: list with probability values
        return roulette proportions"""
    n = len(pi)
    ans = []
    
    for i in range(n):
        ans.append( sum([i for i in pi[:i+1]]) )
    return ans 

# Roulette Wheel 
def Roulette(ppi, Pop):
    """ ppi: list of roulette proportions
        Pop: list of corresponding item   [item1, ... , itemN] """
    
    n = len(ppi)
    ra = random.random()
    
    for i in range(n):
        if i == 0 :
            if ra > 0 and ra < ppi[i]:
                return Pop[i]
        else:
            if ra > ppi[i-1] and ra < ppi[i]:
                return Pop[i]

# Calculate Route Cost and Rank Ants

In [17]:
# calculate cost of each route
def Cost(Pop, graph):
    """ Pop: List of All Items in the e.g [[item1], ... , [itemN]]
    graph: cost matrix or graph 
    returns a cost vector for corresponding item """
    
    Cvector = []
    
    for i in range(len(Pop)):
        route = Pop[i]
        cost = 0
        
        for j in range(len(route)-1):
            cost += graph[route[j]][route[j+1]]
        cost += graph[route[0]][route[len(route)-1]]   
        Cvector.append(cost)
        
    return Cvector

# Sort Chromosomes from Best to Worst
def Rank(Pop, graph):
    """ returns sorted Ants """
    cost = Cost(Pop, graph)
    ans = [ x for _,x in sorted(zip(cost, Pop))]
    #cost = [ _ for _,x in sorted(zip(cost, Pop))]  # need to use the true cost
    return ans

# Initialize Pheromone 

In [18]:
# AS initialization
def TSPher(graph):
    
    n = len(graph)
    route = [i for i in range(n)]
    random.shuffle(route)
    
    cost = Cost([route], graph)[0]
    pher = [[cost for i in range(n)] for j in range(n)]
    
    return pher

# EAS initialization
def EASTSPher(graph, e, m, rho):
    
    n = len(graph)
    route = [i for i in range(n)]
    random.shuffle(route)
    
    cost = Cost([route], graph)[0]
    
    numer = e + m
    den = rho*cost
    pher = [[numer/den for i in range(n)] for j in range(n)]
    
    return pher


# EAS initialization
def MMTSPher(graph, tmax, rho = 0.1):
    # small evaporation 
    
    n = len(graph)
    pher = [[(1-rho)*tmax for i in range(n)] for j in range(n)]
    
    return pher

# Calculate Transition Probability

In [19]:
# Transition Probability
def TransitionP(connections, alpha, beta):
    """ Takes a list of tuples [(pheromone, distance, hob), ... , (pheromone, distance, hob)]
        return trasition probability for each hob [(probability, hob), ... , (probability, hob)]"""
    
    total = sum( [ (i[0]**alpha)*(i[1]**beta) for i in connections])    # sum heuristic and pheromone info
    prob = [( (((i**alpha)*(j**beta))/total) , k) for i,j,k in connections ]  # probability of each hob
    
    return prob

# pheromone, distance and hob information
def DPH(phermatrix, graph, connections, preshob):
    """ DPH(Distance Pheromone hob)
        takes a pheromone matrix
        graph matrix 
        connections in graph to use 
        present hob in graph
        and return the pheromone, distance and hob [(pheromone, distance, hob), ... , (pheromone, distance, hob)]"""
    
    dph = []
    for i in range(len(connections)):
        if connections[i] > 0:
            dph.append( (phermatrix[preshob][i], 1/graph[preshob][i], i) )
            
    #dph = [(phermatrix[preshob][i], graph[preshob][i], i) for i in range(len(connections)) if connections[i] > 0 ]
    
    return dph

def Disconnect(visited, connections):
    """ Disconnects already visited hobs
    visited: already visited hobs
    connections: connection vector with 0: no connection x: length of connection"""
    
    for i in visited:
        connections[i] = 0
        
    return connections

# Find Path 

In [20]:
def FindPath(phermatrix, graph, takeoff, alpha = 2, beta = 2):
    
    path = []
    path.append(takeoff)
    
    while len(path) != len(graph):
        
        Cons = graph[takeoff].copy()
        tabu = path.copy()
        Cons = Disconnect(tabu, Cons)
        HP = DPH(phermatrix, graph, Cons, takeoff)
        prob = TransitionP(HP, alpha, beta)
        takeoff = Roulette(PPi([i[0] for i in prob]), [i[1] for i in prob])
        
        path.append(takeoff)
 
    return path

# Get Elite Route and Connections

In [21]:
def Elite(Elite, ant, graph):
    
    if Cost([ant], graph)[0] < Cost([Elite], graph)[0]:
        return ant, Cost([ant], graph)[0]
    else:
        return Elite, 0

def connections(L):
    """L is a list
    one way connection """
    
    cons = []
    for i in range(1,len(L)):
        cons.append( (L[i-1], L[i]) )
    
    cons.append((L[-1], L[0]))
    
    return cons

def connectionsE(L):
    """L is a list
    Two way connection """
    
    cons = []
    for i in range(1,len(L)):
        cons.append( (L[i-1], L[i]) )
        cons.append( (L[i], L[i-1]) )
    
    cons.append((L[-1], L[0]))
    cons.append((L[0], L[1]))
    
    return cons

# Update Pheromone 

In [22]:
# Update Pheromone in visited arcs

def UpPheromone(route, matrix):
    """route : route taken
    matrix: pheromone matrix"""
    
    tau = 1/Cost([route], matrix)[0]
    #tau = 1
    
    for i in range(len(route)-1):
        
        matrix[route[i]][route[i+1]] += tau
        matrix[route[i+1]][route[i]] += tau
    
    # add pheromone to last and first route for TSP
    matrix[route[-1]][route[0]] += tau
    matrix[route[0]][route[-1]] += tau

    return matrix

# Elite Ant System
def RBASUpPheromone(route, matrix, w, r):
    """route : route taken
    matrix: pheromone matrix"""
    
    tau = 1/Cost([route], matrix)[0]
    #tau = 1
    
    for i in range(len(route)-1):
        matrix[route[i]][route[i+1]] += (w-r)*tau 
        matrix[route[i+1]][route[i]] += (w-r)*tau 
        
    matrix[route[-1]][route[0]] += (w-r)*tau
    matrix[route[0]][route[-1]] += (w-r)*tau

    return matrix

# Ranked based Ant System
def ElitePheromone(Elite, matrix, w):
    """route : route taken
    matrix: pheromone matrix"""
    
    bstau = 1/Cost([Elite], matrix)[0]
    #tau = 1
    
    for i in range(len(Elite)-1):
        matrix[Elite[i]][Elite[i+1]] += (w*bstau) 
        matrix[Elite[i+1]][Elite[i]] += (w*bstau) 
        
    matrix[Elite[-1]][Elite[0]] += (w*bstau)
    matrix[Elite[0]][Elite[-1]] += (w*bstau)

    return matrix

# Min-Max Ant System
def MMPheromone(Elite, matrix):
    """route : route taken
    matrix: pheromone matrix"""
    
    T = Cost([Elite], matrix)[0]
    bstau = 1/T
    #tau = 1
    
    for i in range(len(Elite)-1):
        matrix[Elite[i]][Elite[i+1]] += (bstau) 
        matrix[Elite[i+1]][Elite[i]] += (bstau) 
        
    matrix[Elite[-1]][Elite[0]] += (bstau)
    matrix[Elite[0]][Elite[-1]] += (bstau)

    return matrix

# Evaporate Pheromone 

In [23]:
def EvPheromone(matrix, rho, tmax, tmin):
    
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j] > 0:
                matrix[i][j] = (1-rho)*matrix[i][j]
            else:
                matrix[i][j] = tmin
    return matrix

def EvPheromoneNeg(matrix, rho, tmax, tmin):
    
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            matrix[i][j] = (1-rho)*matrix[i][j]
            
            if matrix[i][j] > tmax:
                matrix[i][j] = tmax
            
            if matrix[i][j] < tmin:
                matrix[i][j] = tmin
        
    return matrix

# Generate a Toy Symmetric TSP Problem 

In [24]:
# A random graph
def Graph(dim, bounds):
    b = [(i, str(i)) for i in range(dim)]   
    matrix = []
    
    for i,j in b:
        j=[]
        if i == 0:
            j.append(0)
            matrix.append(j)
        else:
            for k in range(i+1):
                if k == i:
                    j.append(0)
                else:
                    j.append(random.choice([random.randint(bounds[0], bounds[1])]))  # route length
            matrix.append(j)
            
    M = matrix        
    for i in range(len(M)):
        
        for j in range(1,len(M)-len(M[i])+1):
            M[i].append(M[i+j][i]) 
            
    return M

# Ant System Algorithm

In [25]:
def AS(Ngraph, ants, alpha = 1, beta = 3, rho = 0.5, a = 10, MaxStag = 10, runs = 50, Pher = None):
    
    
    GOAT = [i for i in range(len(Ngraph))]  # initial best ant
    tmax = 1/(rho*(Cost([GOAT], Ngraph)[0]))
    tmin = tmax/a
    
    # to compare if the best-so-far has changed
    PGOAT = GOAT.copy()
    
    # Initialize Pheromone
    if Pher == None:
        #Pher = TSPher(Ngraph)
        Pher = MMTSPher(Ngraph, tmax)
        
    # Stagnation Count   MaxStag is maximum attenable stag to initiate reinitalization
    stag = 0
        
    starthob = random.choice([i for i in range(len(Ngraph))])

    i = 0
    while i < runs:
        Ants = []
        #starthob = random.choice([i for i in range(len(Ngraph))])
        
        for j in range(ants):
            stof = FindPath(Pher, Ngraph, starthob, alpha, beta)
            Ants.append(stof)
            GOAT, changed = Elite(GOAT, stof, Ngraph)
            
        #readjust pheromone limits
        if GOAT != PGOAT:
            tmax =  1/(rho*(Cost([GOAT], Ngraph)[0]))
            tmin = (tmax*(1 - (0.05**(1/len(Ngraph) ) ) ) )/(len(Ngraph)/2 - 1)
            stag = 0
        
        # update stagnation count and reinitialize pheromone if necessary
        if GOAT == PGOAT:
            stag += 1
            if stag == MaxStag:
                Pher = MMTSPher(Ngraph, tmax)
                print(i, " Stagnation Found at :", stag , "  Reinitialization Innitaited")
                stag = 0
        
        PGOAT = GOAT.copy()
        # Rank Ants by sorting and keep top w-1
        Ranked = Rank(Ants, Ngraph)[0]
        B = random.choice([Ranked, GOAT])

        #Pheromone update
        for r,j in enumerate([B]):
            r += 1
            MMPheromone(j, Pher)
        
        #ElitePheromone(GOAT, Pher, w)
        
        #Pheromone evaporation
        #EvPheromone(Pher, rho)
        EvPheromoneNeg(Pher, rho, tmax, tmin)
        
        if i%int(runs*0.05) == 0:
            C = Cost(Ants, Ngraph)
            E = Cost([GOAT], Ngraph)[0]
            print("Evolution ", i, " Elite Cost = ", E,  " Minimum Cost = ", min(C), "  and Maximum Cost = ", max(C))
            #print("<<<<<<<<  The Best Route IS  >>>>>>>> ", GOAT)
        i += 1 

    C = Cost(Ants, Ngraph)    
    print("Minimum Cost Found = ", min(C), "Maximum Cost Found = ", max(C))
    return np.array(Ants), min(C) #, np.array(Pher)

# Example on the Toy Problem

In [26]:
# Toy Network graph 
D = 10
bounds = (2,10)
random.seed(10)
graph = Graph(D, bounds)

np.array(graph)

array([[ 0,  2,  9,  9,  7,  8,  5, 10,  6,  9],
       [ 2,  0,  5,  4,  5,  6,  8,  8, 10,  6],
       [ 9,  5,  0, 10,  2,  9,  2,  3,  4, 10],
       [ 9,  4, 10,  0,  4,  6,  4, 10,  7,  3],
       [ 7,  5,  2,  4,  0,  4,  6,  5,  3,  9],
       [ 8,  6,  9,  6,  4,  0,  5,  5,  9,  4],
       [ 5,  8,  2,  4,  6,  5,  0,  2,  5,  4],
       [10,  8,  3, 10,  5,  5,  2,  0,  8,  7],
       [ 6, 10,  4,  7,  3,  9,  5,  8,  0,  8],
       [ 9,  6, 10,  3,  9,  4,  4,  7,  8,  0]])

In [27]:
# Find Shortest Path with the Algorithm

ants = len(graph)
alpha = 1
beta = 3
rho = 0.02
count = len(graph)*3
a = 10
runs = 200
count = int(runs/4)

AS(graph, ants, alpha, beta, rho, a, count, runs)

Evolution  0  Elite Cost =  37  Minimum Cost =  37   and Maximum Cost =  54
Evolution  10  Elite Cost =  33  Minimum Cost =  37   and Maximum Cost =  46
Evolution  20  Elite Cost =  33  Minimum Cost =  35   and Maximum Cost =  45
Evolution  30  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  51
Evolution  40  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  46
Evolution  50  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  43
54  Stagnation Found at : 50   Reinitialization Innitaited
Evolution  60  Elite Cost =  33  Minimum Cost =  36   and Maximum Cost =  47
Evolution  70  Elite Cost =  33  Minimum Cost =  36   and Maximum Cost =  49
Evolution  80  Elite Cost =  33  Minimum Cost =  36   and Maximum Cost =  53
Evolution  90  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  47
Evolution  100  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  47
104  Stagnation Found at : 50   Reinitialization Innitaited
Evolution  110  Elite Cost =  33  

(array([[0, 1, 3, 9, 5, 7, 6, 2, 4, 8],
        [0, 1, 2, 6, 7, 9, 3, 4, 8, 5],
        [0, 1, 4, 2, 6, 7, 5, 9, 3, 8],
        [0, 1, 3, 9, 5, 4, 2, 6, 7, 8],
        [0, 1, 3, 9, 5, 4, 8, 2, 6, 7],
        [0, 1, 4, 2, 6, 7, 5, 9, 3, 8],
        [0, 1, 9, 3, 6, 7, 2, 4, 8, 5],
        [0, 1, 3, 9, 8, 4, 2, 6, 7, 5],
        [0, 1, 3, 9, 5, 7, 6, 2, 4, 8],
        [0, 1, 3, 9, 5, 6, 7, 2, 4, 8]]), 33)

# Soving Real TSP problems 

In [28]:
# att48

import RouteMatrix as RM
path = './Data/att48.txt'
graph = RM.TSRM(path)


ants = len(graph)
alpha = 1
beta = 3
rho = 0.02
a = len(graph)
runs = 1000
counts = int(runs/5)

AS(graph, ants, alpha, beta, rho, a, counts, runs)

Evolution  0  Elite Cost =  47020.699914943194  Minimum Cost =  47020.699914943194   and Maximum Cost =  72470.04107041493
Evolution  50  Elite Cost =  38389.77053633088  Minimum Cost =  40709.741310227175   and Maximum Cost =  58677.99157204213
Evolution  100  Elite Cost =  37057.34301137624  Minimum Cost =  40768.90691736174   and Maximum Cost =  60814.80790076877
Evolution  150  Elite Cost =  37057.34301137624  Minimum Cost =  41684.24576961685   and Maximum Cost =  55686.38145533543
Evolution  200  Elite Cost =  37057.34301137624  Minimum Cost =  38409.66223501918   and Maximum Cost =  54948.36123918719
Evolution  250  Elite Cost =  37057.34301137624  Minimum Cost =  41050.83838318591   and Maximum Cost =  53877.74708229429
279  Stagnation Found at : 200   Reinitialization Innitaited
Evolution  300  Elite Cost =  37057.34301137624  Minimum Cost =  46386.21087611488   and Maximum Cost =  66172.97917522848
Evolution  350  Elite Cost =  37057.34301137624  Minimum Cost =  44267.4358882

(array([[ 8,  0,  7, ..., 25, 34, 44],
        [ 8, 11, 46, ..., 24, 28,  1],
        [ 8,  0,  7, ..., 14, 22, 31],
        ...,
        [ 8, 39,  0, ..., 28,  1, 42],
        [ 8,  0, 15, ..., 41,  9,  1],
        [ 8, 37, 30, ..., 11, 40, 20]]), 43362.75018954343)

In [32]:
# burma14

import RouteMatrix as RM
path = './Data/burma14.txt'
graph = RM.TSRM(path)


ants = len(graph)
alpha = 1
beta = 3
rho = 0.02
a = len(graph)
runs = 100
counts = int(runs/5)

AS(graph, ants, alpha, beta, rho, a, counts, runs)

Evolution  0  Elite Cost =  35.106489779157236  Minimum Cost =  35.106489779157236   and Maximum Cost =  47.303009655804935
Evolution  5  Elite Cost =  31.56696162617908  Minimum Cost =  35.066668530493395   and Maximum Cost =  50.057906935140096
Evolution  10  Elite Cost =  31.56696162617908  Minimum Cost =  36.18076873178537   and Maximum Cost =  51.68486668760144
Evolution  15  Elite Cost =  31.56696162617908  Minimum Cost =  34.84243575508273   and Maximum Cost =  43.446058395325686
Evolution  20  Elite Cost =  31.56696162617908  Minimum Cost =  31.56696162617908   and Maximum Cost =  46.98669090734491
22  Stagnation Found at : 20   Reinitialization Innitaited
Evolution  25  Elite Cost =  31.56696162617908  Minimum Cost =  35.15168650335131   and Maximum Cost =  52.39170967014782
Evolution  30  Elite Cost =  31.56696162617908  Minimum Cost =  39.20533471784302   and Maximum Cost =  53.80036151313709
Evolution  35  Elite Cost =  31.56696162617908  Minimum Cost =  35.729416448383844 

(array([[12,  6,  5, 11, 13,  2,  3,  0,  7,  1,  9,  8, 10,  4],
        [12,  6,  7,  0, 10,  8,  9, 11,  5,  4,  3,  2, 13,  1],
        [12,  6,  5, 11,  3, 13,  2,  7, 10,  8,  9,  0,  1,  4],
        [12,  6, 13,  2,  8, 10,  9,  0,  7,  1, 11,  5,  3,  4],
        [12,  6, 10,  8,  7,  0,  5, 11, 13,  1,  2,  3,  4,  9],
        [12,  5, 11, 13,  8, 10,  0,  7,  6,  2,  3,  4,  1,  9],
        [12,  5, 11,  6, 10,  8,  0,  7, 13,  2,  3,  4,  9,  1],
        [12,  6, 11,  5, 13,  1, 10,  8,  7,  0,  2,  3,  4,  9],
        [12,  6,  5, 11, 10,  8,  0,  1,  7, 13,  2,  3,  4,  9],
        [12,  6, 11,  5, 13,  2,  3,  4,  7,  0, 10,  8,  9,  1],
        [12,  6, 11,  5,  2,  3, 13,  1,  0,  7, 10,  8,  9,  4],
        [12,  6,  5, 11, 13,  3,  2,  9, 10,  8,  0,  7,  1,  4],
        [12,  6, 11,  5, 13,  2,  1,  0,  7, 10,  8,  9,  3,  4],
        [12,  6, 11,  5,  4,  3, 13,  2,  1,  8, 10,  7,  0,  9]]),
 34.242085422439025)