# The Elite Ant System Algorithm For The Travelling Salesman Problem

Algorithm from the Book **Ant Colony Optimization by Marco Dorigo and Thomas Stützle**

In [1]:
#----------------------------------------
# Chia E. Tungom
# chemago99@yahoo.com
# July 30th 2020
# Shenzhen China
#----------------------------------------

In [2]:
# import libraries

import numpy as np
import math
import random

# Roulette Wheel for Probability

In [3]:
# probability and selection using roulette wheel 

# Calculate cumulative sum for roulette wheel 
def PPi(pi):
    """ pi: list with probability values
        return roulette proportions"""
    n = len(pi)
    ans = []
    
    for i in range(n):
        ans.append( sum([i for i in pi[:i+1]]) )
    return ans 

# Roulette Wheel 
def Roulette(ppi, Pop):
    """ ppi: list of roulette proportions
        Pop: list of corresponding item   [item1, ... , itemN] """
    
    n = len(ppi)
    ra = random.random()
    
    for i in range(n):
        if i == 0 :
            if ra > 0 and ra < ppi[i]:
                return Pop[i]
        else:
            if ra > ppi[i-1] and ra < ppi[i]:
                return Pop[i]

# Calculate Route Cost and Rank Ants

In [4]:
# calculate cost of each route
def Cost(Pop, graph):
    """ Pop: List of All Items in the e.g [[item1], ... , [itemN]]
    graph: cost matrix or graph 
    returns a cost vector for corresponding item """
    
    Cvector = []
    
    for i in range(len(Pop)):
        route = Pop[i]
        cost = 0
        
        for j in range(len(route)-1):
            cost += graph[route[j]][route[j+1]]
        cost += graph[route[0]][route[len(route)-1]]   
        Cvector.append(cost)
        
    return Cvector

# Sort Chromosomes from Best to Worst
def Rank(Pop, graph):
    """ returns sorted Ants """
    cost = Cost(Pop, graph)
    ans = [ x for _,x in sorted(zip(cost, Pop))]
    #cost = [ _ for _,x in sorted(zip(cost, Pop))]  # need to use the true cost
    return ans

# Initialize Pheromone 

In [5]:
# AS initialization
def TSPher(graph):
    
    n = len(graph)
    route = [i for i in range(n)]
    random.shuffle(route)
    
    cost = Cost([route], graph)[0]
    pher = [[cost for i in range(n)] for j in range(n)]
    
    return pher

# EAS initialization
def EASTSPher(graph, e, m, rho):
    
    n = len(graph)
    route = [i for i in range(n)]
    random.shuffle(route)
    
    cost = Cost([route], graph)[0]
    
    numer = e + m
    den = rho*cost
    pher = [[numer/den for i in range(n)] for j in range(n)]
    
    return pher

# Calculate Transition Probability

In [6]:
# Transition Probability
def TransitionP(connections, alpha, beta):
    """ Takes a list of tuples [(pheromone, distance, hob), ... , (pheromone, distance, hob)]
        return trasition probability for each hob [(probability, hob), ... , (probability, hob)]"""
    
    total = sum( [ (i[0]**alpha)*(i[1]**beta) for i in connections])    # sum heuristic and pheromone info
    prob = [( (((i**alpha)*(j**beta))/total) , k) for i,j,k in connections ]  # probability of each hob
    
    return prob

# pheromone, distance and hob information
def DPH(phermatrix, graph, connections, preshob):
    """ DPH(Distance Pheromone hob)
        takes a pheromone matrix
        graph matrix 
        connections in graph to use 
        present hob in graph
        and return the pheromone, distance and hob [(pheromone, distance, hob), ... , (pheromone, distance, hob)]"""
    
    dph = []
    for i in range(len(connections)):
        if connections[i] > 0:
            dph.append( (phermatrix[preshob][i], 1/graph[preshob][i], i) )
            
    #dph = [(phermatrix[preshob][i], graph[preshob][i], i) for i in range(len(connections)) if connections[i] > 0 ]
    
    return dph

def Disconnect(visited, connections):
    """ Disconnects already visited hobs
    visited: already visited hobs
    connections: connection vector with 0: no connection x: length of connection"""
    
    for i in visited:
        connections[i] = 0
        
    return connections

# Find Path 

In [7]:
def FindPath(phermatrix, graph, takeoff, alpha = 2, beta = 2):
    
    path = []
    path.append(takeoff)
    
    while len(path) != len(graph):
        
        Cons = graph[takeoff].copy()
        tabu = path.copy()
        Cons = Disconnect(tabu, Cons)
        HP = DPH(phermatrix, graph, Cons, takeoff)
        prob = TransitionP(HP, alpha, beta)
        takeoff = Roulette(PPi([i[0] for i in prob]), [i[1] for i in prob])
        
        path.append(takeoff)
 
    return path

# Get Elite Route and Connections

In [8]:
def Elite(Elite, ant, graph):
    
    if Cost([ant], graph)[0] < Cost([Elite], graph)[0]:
        return ant
    else:
        return Elite

def connections(L):
    """L is a list
    one way connection """
    
    cons = []
    for i in range(1,len(L)):
        cons.append( (L[i-1], L[i]) )
    
    cons.append((L[-1], L[0]))
    
    return cons

def connectionsE(L):
    """L is a list
    Two way connection """
    
    cons = []
    for i in range(1,len(L)):
        cons.append( (L[i-1], L[i]) )
        cons.append( (L[i], L[i-1]) )
    
    cons.append((L[-1], L[0]))
    cons.append((L[0], L[1]))
    
    return cons

# Update Pheromone 

In [9]:
# Update Pheromone in visited arcs

def UpPheromone(route, matrix):
    """route : route taken
    matrix: pheromone matrix"""
    
    tau = 1/Cost([route], matrix)[0]
    #tau = 1
    
    for i in range(len(route)-1):
        
        matrix[route[i]][route[i+1]] += tau
        matrix[route[i+1]][route[i]] += tau
    
    # add pheromone to last and first route for TSP
    matrix[route[-1]][route[0]] += tau
    matrix[route[0]][route[-1]] += tau

    return matrix

# Elite Ant System
def RBASUpPheromone(route, matrix, w, r):
    """route : route taken
    matrix: pheromone matrix"""
    
    tau = 1/Cost([route], matrix)[0]
    #tau = 1
    
    for i in range(len(route)-1):
        matrix[route[i]][route[i+1]] += (w-r)*tau 
        matrix[route[i+1]][route[i]] += (w-r)*tau 
        
    matrix[route[-1]][route[0]] += (w-r)*tau
    matrix[route[0]][route[-1]] += (w-r)*tau

    return matrix

# Ranked based Ant System
def ElitePheromone(Elite, matrix, w):
    """route : route taken
    matrix: pheromone matrix"""
    
    bstau = 1/Cost([Elite], matrix)[0]
    #tau = 1
    
    for i in range(len(Elite)-1):
        matrix[Elite[i]][Elite[i+1]] += (w*bstau) 
        matrix[Elite[i+1]][Elite[i]] += (w*bstau) 
        
    matrix[Elite[-1]][Elite[0]] += (w*bstau)
    matrix[Elite[0]][Elite[-1]] += (w*bstau)

    return matrix

# Evaporate Pheromone 

In [10]:
def EvPheromone(matrix, rho):
    
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j] > 0:
                matrix[i][j] = (1-rho)*matrix[i][j]
            else:
                matrix[i][j] = math.exp(-5)
    return matrix

def EvPheromoneNeg(matrix, rho):
    
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            matrix[i][j] = (1-rho)*matrix[i][j]
        
    return matrix

# Generate a Toy Symmetric TSP Problem 

In [11]:
# A random graph
def Graph(dim, bounds):
    b = [(i, str(i)) for i in range(dim)]   
    matrix = []
    
    for i,j in b:
        j=[]
        if i == 0:
            j.append(0)
            matrix.append(j)
        else:
            for k in range(i+1):
                if k == i:
                    j.append(0)
                else:
                    j.append(random.choice([random.randint(bounds[0], bounds[1])]))  # route length
            matrix.append(j)
            
    M = matrix        
    for i in range(len(M)):
        
        for j in range(1,len(M)-len(M[i])+1):
            M[i].append(M[i+j][i]) 
            
    return M

# Ant System Algorithm

In [12]:
def AS(Ngraph, ants, alpha = 1, beta = 3, rho = 0.5, e = 10, w = 2, runs = 50, Pher = None):
    
    if Pher == None:
        #Pher = TSPher(Ngraph)
        Pher = EASTSPher(Ngraph, e, ants, rho)
        
    starthob = random.choice([i for i in range(len(Ngraph))])

    GOAT = [i for i in range(len(Ngraph))]  # initial best ant
    
    i = 0
    while i < runs:
        Ants = []
        #starthob = random.choice([i for i in range(len(Ngraph))])
        
        for j in range(ants):
            stof = FindPath(Pher, Ngraph, starthob, alpha, beta)
            Ants.append(stof)
            GOAT = Elite(GOAT, stof, Ngraph)
            
        # Rank Ants by sorting and keep top w-1
        Ranked = Rank(Ants, graph)[:w-1]
        
        #Pheromone update
        for r,j in enumerate(Ranked):
            r += 1
            RBASUpPheromone(j, Pher, w, r)
        
        ElitePheromone(GOAT, Pher, w)
        
        #Pheromone evaporation
        #EvPheromone(Pher, rho)
        EvPheromoneNeg(Pher, rho)
        
        if i%int(runs*0.05) == 0:
            C = Cost(Ants, Ngraph)
            E = Cost([GOAT], Ngraph)[0]
            print("Evolution ", i, " Elite Cost = ", E,  " Minimum Cost = ", min(C), "  and Maximum Cost = ", max(C))
            #print("<<<<<<<<  The Best Route IS  >>>>>>>> ", GOAT)
        i += 1 

    C = Cost(Ants, Ngraph)    
    print("Minimum Cost Found = ", min(C), "Maximum Cost Found = ", max(C))
    return np.array(Ants), min(C) #, np.array(Pher)

# Example on the Toy Problem

In [13]:
# Toy Network graph 
D = 10
bounds = (2,10)
random.seed(10)
graph = Graph(D, bounds)

np.array(graph)

array([[ 0,  2,  9,  9,  7,  8,  5, 10,  6,  9],
       [ 2,  0,  5,  4,  5,  6,  8,  8, 10,  6],
       [ 9,  5,  0, 10,  2,  9,  2,  3,  4, 10],
       [ 9,  4, 10,  0,  4,  6,  4, 10,  7,  3],
       [ 7,  5,  2,  4,  0,  4,  6,  5,  3,  9],
       [ 8,  6,  9,  6,  4,  0,  5,  5,  9,  4],
       [ 5,  8,  2,  4,  6,  5,  0,  2,  5,  4],
       [10,  8,  3, 10,  5,  5,  2,  0,  8,  7],
       [ 6, 10,  4,  7,  3,  9,  5,  8,  0,  8],
       [ 9,  6, 10,  3,  9,  4,  4,  7,  8,  0]])

In [14]:
# Find Shortest Path with the Algorithm

ants = len(graph)
alpha = 1
beta = 3
rho = 0.1
e = len(graph)
w = 6
runs = 200

AS(graph, ants, alpha, beta, rho, e, w, runs)

Evolution  0  Elite Cost =  34  Minimum Cost =  34   and Maximum Cost =  47
Evolution  10  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  46
Evolution  20  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  50
Evolution  30  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  38
Evolution  40  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  40
Evolution  50  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  60  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  70  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  80  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  90  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  100  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  110  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  33
Evolution  120  Elite Cost =  33  Minimum Cost =  33   and Maximum Cost =  

(array([[6, 7, 5, 9, 3, 1, 0, 8, 4, 2],
        [6, 7, 5, 9, 3, 1, 0, 8, 4, 2],
        [6, 2, 4, 8, 0, 1, 3, 9, 5, 7],
        [6, 7, 5, 9, 3, 1, 0, 8, 4, 2],
        [6, 7, 5, 9, 3, 1, 0, 8, 4, 2],
        [6, 2, 4, 8, 0, 1, 3, 9, 5, 7],
        [6, 2, 4, 8, 0, 1, 3, 9, 5, 7],
        [6, 7, 5, 9, 3, 1, 0, 8, 4, 2],
        [6, 7, 5, 9, 3, 1, 0, 8, 4, 2],
        [6, 7, 5, 9, 3, 1, 0, 8, 4, 2]]), 33)

# Soving Real TSP problems 

In [15]:
# att48

import RouteMatrix as RM
path = './Data/att48.txt'
graph = RM.TSRM(path)


ants = len(graph)
alpha = 1
beta = 4
rho = 0.1
e = len(graph)
runs = 100

AS(graph, ants, alpha, beta, rho, e, w, runs)

Evolution  0  Elite Cost =  40873.69930102346  Minimum Cost =  40873.69930102346   and Maximum Cost =  59334.770230493166
Evolution  5  Elite Cost =  38830.61385168444  Minimum Cost =  38830.61385168444   and Maximum Cost =  49374.885866902114
Evolution  10  Elite Cost =  38441.557957392084  Minimum Cost =  38830.61385168444   and Maximum Cost =  42467.73432400471
Evolution  15  Elite Cost =  37961.64930743689  Minimum Cost =  37961.64930743689   and Maximum Cost =  48022.3072769881
Evolution  20  Elite Cost =  37803.91016544185  Minimum Cost =  37803.91016544185   and Maximum Cost =  48073.39387653163
Evolution  25  Elite Cost =  37601.22728588455  Minimum Cost =  37601.22728588455   and Maximum Cost =  46595.67771202913
Evolution  30  Elite Cost =  37572.59341314453  Minimum Cost =  37572.59341314453   and Maximum Cost =  46071.995798296964
Evolution  35  Elite Cost =  37272.94208010267  Minimum Cost =  37272.94208010267   and Maximum Cost =  51821.177220826685
Evolution  40  Elite C

(array([[13, 24, 12, ..., 38, 47,  4],
        [13, 24, 12, ..., 38, 47,  4],
        [13, 24, 12, ..., 38, 47,  4],
        ...,
        [13, 24, 12, ..., 38, 47,  4],
        [13, 24, 12, ..., 38, 47,  4],
        [13, 24, 12, ..., 38, 47,  4]]), 36781.25609730937)

In [16]:
# burma14

import RouteMatrix as RM
path = './Data/burma14.txt'
graph = RM.TSRM(path)


ants = len(graph)
alpha = 1
beta = 4
rho = 0.1
e = len(graph)
runs = 1000

AS(graph, ants, alpha, beta, rho, e, w, runs)

Evolution  0  Elite Cost =  32.925726275804955  Minimum Cost =  32.925726275804955   and Maximum Cost =  50.49403242283327
Evolution  50  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  40.81254698210478
Evolution  100  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  31.226915109427544
Evolution  150  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  31.226915109427544
Evolution  200  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  31.226915109427544
Evolution  250  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  31.226915109427544
Evolution  300  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  31.226915109427544
Evolution  350  Elite Cost =  31.226915109427544  Minimum Cost =  31.226915109427544   and Maximum Cost =  31.2269151094275

(array([[ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  3,  2, 13,  1,  9,  8, 10,  0,  7, 12,  6, 11,  5],
        [ 4,  5, 11,  6, 12,  7,  0, 10,  8,  9,  1, 13,  2,  3],
        [ 4,  3,  2, 13,  1,  9,  8, 10,  0,  7, 12,  6, 11,  5]]),
 31.226915109427544)